# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maharaja/fri-semantic-parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maharaja/fri-semantic-parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maharaja/fri-semantic-parser/CMakeFiles /home/maharaja/fri-semantic-parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maharaja/fri-semantic-parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Lexicon.o: Lexicon.cpp.o

.PHONY : Lexicon.o

# target to build an object file
Lexicon.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Lexicon.cpp.o
.PHONY : Lexicon.cpp.o

Lexicon.i: Lexicon.cpp.i

.PHONY : Lexicon.i

# target to preprocess a source file
Lexicon.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Lexicon.cpp.i
.PHONY : Lexicon.cpp.i

Lexicon.s: Lexicon.cpp.s

.PHONY : Lexicon.s

# target to generate assembly for a file
Lexicon.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Lexicon.cpp.s
.PHONY : Lexicon.cpp.s

Ontology.o: Ontology.cpp.o

.PHONY : Ontology.o

# target to build an object file
Ontology.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Ontology.cpp.o
.PHONY : Ontology.cpp.o

Ontology.i: Ontology.cpp.i

.PHONY : Ontology.i

# target to preprocess a source file
Ontology.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Ontology.cpp.i
.PHONY : Ontology.cpp.i

Ontology.s: Ontology.cpp.s

.PHONY : Ontology.s

# target to generate assembly for a file
Ontology.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Ontology.cpp.s
.PHONY : Ontology.cpp.s

ParseNode.o: ParseNode.cpp.o

.PHONY : ParseNode.o

# target to build an object file
ParseNode.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParseNode.cpp.o
.PHONY : ParseNode.cpp.o

ParseNode.i: ParseNode.cpp.i

.PHONY : ParseNode.i

# target to preprocess a source file
ParseNode.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParseNode.cpp.i
.PHONY : ParseNode.cpp.i

ParseNode.s: ParseNode.cpp.s

.PHONY : ParseNode.s

# target to generate assembly for a file
ParseNode.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParseNode.cpp.s
.PHONY : ParseNode.cpp.s

SemanticNode.o: SemanticNode.cpp.o

.PHONY : SemanticNode.o

# target to build an object file
SemanticNode.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SemanticNode.cpp.o
.PHONY : SemanticNode.cpp.o

SemanticNode.i: SemanticNode.cpp.i

.PHONY : SemanticNode.i

# target to preprocess a source file
SemanticNode.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SemanticNode.cpp.i
.PHONY : SemanticNode.cpp.i

SemanticNode.s: SemanticNode.cpp.s

.PHONY : SemanticNode.s

# target to generate assembly for a file
SemanticNode.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SemanticNode.cpp.s
.PHONY : SemanticNode.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... Lexicon.o"
	@echo "... Lexicon.i"
	@echo "... Lexicon.s"
	@echo "... Ontology.o"
	@echo "... Ontology.i"
	@echo "... Ontology.s"
	@echo "... ParseNode.o"
	@echo "... ParseNode.i"
	@echo "... ParseNode.s"
	@echo "... SemanticNode.o"
	@echo "... SemanticNode.i"
	@echo "... SemanticNode.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

